apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sipp
  name: sipp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sipp
  template:
    metadata:
      labels:
        app: sipp
    spec:
      containers:
      - image: chetangautamm/repo:sipp.v3
        imagePullPolicy: Always
        name: sipp


